name: Bug Report
description: If you experienced a bug while playing with Immersive Petroleum
labels: ["Bug :lady_beetle:"]
body:
  - type: markdown
    attributes:
      value: |
        Before reporting, please use the search function to make sure an issue hasn't been reported already.
        This avoids duplicates.

  - type: dropdown
    attributes:
      label: Minecraft Version
      description: |
        Select the Minecraft version.
        
        *If your version does not show up here, support for it has been closed.*
      options: [1.16.5]
    validations:
      required: true

  - type: input
    attributes:
      label: Immersive Engineering Version
      description: |
        The Immersive Engineering version you are using.
        
        *Saying "latest" is not valid.*
      placeholder: "xx.xx.xx-xxx"
    validations:
      required: true

  - type: input
    attributes:
      label: Immersive Petroleum Version
      description: |
        The Immersive Petroleum version you are using.
        
        *Saying "latest" is not valid.*
      placeholder: "xx.xx.xx-xxx"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Current Behaviour
      description: "A concise description of what you're experiencing. Please provide screenshots and videos if possible."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behaviour
      description: A concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproduction Steps
      description: |
        Explain in easy steps how to reproduce this issue.
        Provide pictures if you believe that they help with visualization.
      placeholder: |
        1. First I did...
        2. Then I did...
        3. And then it broke
    validations:
      required: true

  - type: input
    attributes:
      label: Debug Crash Log
      description: |
        You can generate a debug crashlog ingame by holding down F3 and C for about 10 seconds.
        The log contains a lot of useful information, such as your complete mod list, and certain technical details about your PC.
        Please upload that log to pastebin.com, gist.github.com or a similar site and enter the link here.
      placeholder: <gist or pastebin link>
    validations:
      required: true

  - type: textarea
    attributes:
      label: Information for the reader.
      description: |
        **Do not remove/edit the text contained within this!**
        *It has its purpose!*
      value: |
        * Add a :thumbsup: to the bug report if you are also affected. This helps show the severity of this bug report and doesn't clutter the comments.
        * Add a comment *if* you have any insights or background information that *isn't already part of the conversation*.
    validations:
      required: false
