name: Crash Report
description: If your game crashed while playing with Immersive Petroleum
labels: ["Crash :boom:"]
body:
  - type: markdown
    attributes:
      value: |
        Before reporting, please use the search function to make sure an issue hasn't been reported already.
        This avoids duplicates.

  - type: dropdown
    attributes:
      label: Minecraft Version
      description: |
        Select the Minecraft version.
        
        *If your version does not show up here, support for it has been closed.*
      options: [1.16.5]
    validations:
      required: true

  - type: input
    attributes:
      label: Immersive Engineering Version
      description: |
        The Immersive Engineering version you are using.
        
        *Saying "latest" is not valid.*
      placeholder: "xx.xx.xx-xxx"
    validations:
      required: true

  - type: input
    attributes:
      label: Immersive Petroleum Version
      description: |
        The Immersive Petroleum version you are using.
        
        *Saying "latest" is not valid.*
      placeholder: "xx.xx.xx-xxx"
    validations:
      required: true

  - type: textarea
    id: how-it-happened
    attributes:
      label: How did it happen?
      description: |
        Did you crash on starting the game, loading your world?
        Were you using a specific block or item? Be as precise as possible please!
    validations:
      required: true

  - type: input
    attributes:
      label: Crash Log
      description: |
        If your game crashed, it will have created a file in the folder `crash-reports` in your Minecraft instance.
        Please upload that log to [Gist](https://gist.github.com/), [Pastebin](https://pastebin.com/) or a similar site and enter the link here.
      placeholder: <gist or pastebin link>
    validations:
      required: true
