name: Feature Suggestion
description: Do you have a Feature idea you'd like to tell me about?
title: "[Suggestion] TitleHere"
labels: Enhancement
body:
  - type: checkboxes
    attributes:
      label: Does this suggestion already exist?
      description: "Please search to see if your idea has already been talked about."
      options:
        - label: Yes, i have searched for already existing suggestions and found none.
          required: true
  - type: textarea
    attributes:
      label: Feature Explanation
      description: "*Tip: You can attach images by clicking this area to highlight it and then dragging files in.*"
    validations:
      required: true
